web:
  build: .
  environment:
    MYENV: JVIS
  volumes:
    - .:/code
web_migrate:
  extends:
    service: web
  command: python3 manage.py migrate
web_run:
  extends:
    service: web
  command: python3 manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
