# Generated by Django 3.2 on 2021-09-01 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_box_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['up']},
        ),
        migrations.RemoveField(
            model_name='box',
            name='active',
        ),
        migrations.RemoveField(
            model_name='box',
            name='group',
        ),
        migrations.RemoveField(
            model_name='box',
            name='user',
        ),
        migrations.CreateModel(
            name='BoxComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.box')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
