# Generated by Django 3.2 on 2021-09-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210901_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
