# Generated by Django 3.2 on 2021-09-01 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_alter_box_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='box',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BoxComments',
        ),
    ]
