# Generated by Django 3.2 on 2021-09-02 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210901_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(blank=True, max_length=200)),
                ('extra', models.TextField(blank=True, null=True)),
                ('cBox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.box')),
            ],
        ),
    ]
