# Generated by Django 3.2 on 2021-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_boxservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['state']},
        ),
        migrations.RemoveField(
            model_name='box',
            name='up',
        ),
        migrations.RemoveField(
            model_name='box',
            name='version',
        ),
        migrations.RemoveField(
            model_name='boxservice',
            name='extra',
        ),
        migrations.AddField(
            model_name='box',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='boxservice',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boxservice',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boxservice',
            name='protocol',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='boxservice',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boxservice',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
