# Generated by Django 3.2 on 2021-09-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210904_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxservice',
            options={},
        ),
    ]
