# Generated by Django 3.2 on 2021-09-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210904_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxservice',
            name='port',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
