# Generated by Django 3.2 on 2021-09-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_boxservice_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxservice',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
