# Generated by Django 3.2 on 2021-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_boxservice_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='pwned',
            field=models.BooleanField(default=False),
        ),
    ]
