# Generated by Django 3.2 on 2021-09-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20210905_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
