# Generated by Django 3.2 on 2021-09-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20210910_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxservice',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
