# Generated by Django 3.2 on 2021-09-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20210911_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxservice',
            name='updated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
