# Generated by Django 3.2 on 2021-09-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_boxservice_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxservice',
            name='updated',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
