# Generated by Django 3.2 on 2021-09-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_boxservice_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='browserupdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxservice',
            name='browserupdate',
            field=models.BooleanField(default=False),
        ),
    ]
