# Generated by Django 3.2 on 2021-09-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20210911_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='browserupdate',
        ),
        migrations.RemoveField(
            model_name='boxservice',
            name='browserupdate',
        ),
    ]
