# Generated by Django 3.2 on 2021-09-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20210911_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='cidr',
            field=models.CharField(blank=True, default='/24', max_length=200, null=True),
        ),
    ]
