# Generated by Django 3.2 on 2021-09-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_box_cidr'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='orderedip',
            field=models.BigIntegerField(blank=True, default=5, null=True),
        ),
    ]
