# Generated by Django 3.2 on 2021-09-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_box_orderedip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['orderedip']},
        ),
        migrations.AlterField(
            model_name='box',
            name='orderedip',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
